### ISSUE TITLE
AttributeError: 'Multicall' object has no attribute 'coroutine'

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#258]
Error prevents Telliot from starting.
start command: `1telliot-feeds -a mumbai2 report -p YOLO -wp 240`

```
ERROR   | telliot_core | Exception occurred in telliot-core app
ERROR   | telliot_core | <class 'AttributeError'>
ERROR   | telliot_core | 'Multicall' object has no attribute 'coroutine'
ERROR   | telliot_core | ['  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feeds/cli/commands/report.py", line 397, in report\n    await reporter.report()\n', '  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feeds/reporters/tellorflex.py", line 339, in report\n    _, _ = await self.report_once()\n', '  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feeds/reporters/interval.py", line 313, in report_once\n    datafeed = await self.fetch_datafeed()\n', '  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feeds/reporters/tellorflex.py", line 239, in fetch_datafeed\n    suggested_qtag, autopay_tip = await autopay_suggested_report(self.autopay)\n', '  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feeds/reporters/reporter_autopay_utils.py", line 359, in autopay_suggested_report\n    singletip_dict = await get_one_time_tips(autopay)\n', '  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feeds/reporters/reporter_autopay_utils.py", line 319, in get_one_time_tips\n    return await one_time_tips.get_current_tip()\n', '  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feeds/reporters/reporter_autopay_utils.py", line 282, in get_current_tip\n    data = await multi_call.coroutine()\n']
Traceback (most recent call last):
  File "/home/ubuntu/tenv/bin/telliot-feeds", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_core/cli/utils.py", line 18, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feeds/cli/commands/report.py", line 397, in report
    await reporter.report()
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feeds/reporters/tellorflex.py", line 339, in report
    _, _ = await self.report_once()
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feeds/reporters/interval.py", line 313, in report_once
    datafeed = await self.fetch_datafeed()
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feeds/reporters/tellorflex.py", line 239, in fetch_datafeed
    suggested_qtag, autopay_tip = await autopay_suggested_report(self.autopay)
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feeds/reporters/reporter_autopay_utils.py", line 359, in autopay_suggested_report
    singletip_dict = await get_one_time_tips(autopay)
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feeds/reporters/reporter_autopay_utils.py", line 319, in get_one_time_tips
    return await one_time_tips.get_current_tip()
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/telliot_feeds/reporters/reporter_autopay_utils.py", line 282, in get_current_tip
    data = await multi_call.coroutine()
AttributeError: 'Multicall' object has no attribute 'coroutine'
```

**Comment by akremstudy** [comment]
I'm unable to recreate this error and can't figure out why there is an AttributeError when the coroutine method is part of the Multicall object (https://github.com/banteg/multicall.py/blob/e3d89e88c76cc5876ab6af7578ea2d50f6585362/multicall/multicall.py#L61).

**Comment by spuddyminer** [comment]
Fixed this by updating the pip package `multicall 0.3.0` to `multicall==0.5.1`
