### ISSUE TITLE
ERROR   | telliot_core | argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#304]
New error related to Bittrex(?)
start command: `telliot-feeds -a mumbai5 report -qt usdc-usd-spot -p YOLO`
versions: 
telliot-core.git@ f9016abce2b4276fd4f61ed411546e10b0b75bcc
telliot-feeds.git@ 01a6209b799cb78a6dd5de62e3aae1f111c1b5f8

```
ERROR   | telliot_core | Exception occurred in telliot-core app
ERROR   | telliot_core | <class 'TypeError'>
ERROR   | telliot_core | argument of type 'NoneType' is not iterable
ERROR   | telliot_core | ['  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 402, in report\n    await reporter.report()\n', '  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/reporters/tellorflex.py", line 342, in report\n    _, _ = await self.report_once()\n', '  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 329, in report_once\n    await datafeed.source.fetch_new_datapoint()\n', '  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/sources/price_aggregator.py", line 78, in fetch_new_datapoint\n    datapoints = await self.update_sources()\n', '  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/sources/price_aggregator.py", line 64, in update_sources\n    inputs = await gather_inputs()\n', '  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/sources/price_aggregator.py", line 61, in gather_inputs\n    datapoints = await asyncio.gather(*[source.fetch_new_datapoint() for source in sources])\n', '  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/pricing/price_source.py", line 32, in fetch_new_datapoint\n    datapoint = await self.service.get_price(self.asset, self.currency)\n', '  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/sources/price/spot/bittrex.py", line 50, in get_price\n    if "restrictions that prevent you from accessing the site" in d["exception"].strerror:\n']
Traceback (most recent call last):
  File "/Users/sloetter/Projects/tenv3/bin/telliot-feeds", line 8, in <module>
    sys.exit(main())
  File "/Users/sloetter/Projects/tenv3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sloetter/Projects/tenv3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/sloetter/Projects/tenv3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sloetter/Projects/tenv3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sloetter/Projects/tenv3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sloetter/Projects/tenv3/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sloetter/Projects/telliot-core/src/telliot_core/cli/utils.py", line 18, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/Users/sloetter/.pyenv/versions/3.9.13/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/sloetter/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 402, in report
    await reporter.report()
  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/reporters/tellorflex.py", line 342, in report
    _, _ = await self.report_once()
  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 329, in report_once
    await datafeed.source.fetch_new_datapoint()
  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/sources/price_aggregator.py", line 78, in fetch_new_datapoint
    datapoints = await self.update_sources()
  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/sources/price_aggregator.py", line 64, in update_sources
    inputs = await gather_inputs()
  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/sources/price_aggregator.py", line 61, in gather_inputs
    datapoints = await asyncio.gather(*[source.fetch_new_datapoint() for source in sources])
  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/pricing/price_source.py", line 32, in fetch_new_datapoint
    datapoint = await self.service.get_price(self.asset, self.currency)
  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/sources/price/spot/bittrex.py", line 50, in get_price
    if "restrictions that prevent you from accessing the site" in d["exception"].strerror:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by spuddyminer** [comment]
i think this was a problem with my machine only. will reopen if needed
