### ISSUE TITLE
--help is broken (Can't report?)

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#397]
Calling the help flag results in the following traceback:

```
(tenv5) sloetter@shadow projects % telliot-feeds report --help
Traceback (most recent call last):
  File "/Users/sloetter/.pyenv/versions/3.9.13/bin/telliot-feeds", line 5, in <module>
    from telliot_feeds.cli.main import main
  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/cli/main.py", line 13, in <module>
    from telliot_feeds.cli.commands.report import report
  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 32, in <module>
    from telliot_feeds.utils.cfg import check_endpoint
  File "/Users/sloetter/Projects/telliot-feeds/src/telliot_feeds/utils/cfg.py", line 9, in <module>
    from simple_term_menu import TerminalMenu
ModuleNotFoundError: No module named 'simple_term_menu'
```

Versions: 
telliot-core @53728536f28d440e052adf9919e345fd4fdec349
telliot-feeds @34921ad5fc14479e05e98fc77504cf386fdf5b4c

**Comment by oraclown** [comment]
Closing bc we discussed on discord. Probs need to update dependencies (`pip install -e .`)
