### ISSUE TITLE
KeyError: 'ampleforth-custom-price' (suggested from catalog)

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#402]
Start command: `telliot-feeds -a mumbai4 report -qt eth-usd-spot -p YOLO -wp 480`

versions: 
telliot-core.git@53728536f28d440e052adf9919e345fd4fdec349
telliot-feeds.git@c11782b461a4127a25e4218730310c02ed5a7495

Telliot errors out on Mumbai with the following traceback:

Full Traceback:
```
Traceback (most recent call last):
  File "/home/ubuntu/tenv3/bin/telliot-feeds", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/tenv3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/tenv3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/tenv3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/tenv3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/tenv3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/tenv3/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/telliot-core/src/telliot_core/cli/utils.py", line 18, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 533, in report
    await reporter.report()
  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/tellorflex.py", line 368, in report
    _, _ = await self.report_once()
  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 317, in report_once
    datafeed = await self.fetch_datafeed()
  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/tellorflex.py", line 258, in fetch_datafeed
    self.datafeed = CATALOG_FEEDS[suggested_qtag]  # type: ignore
KeyError: 'ampleforth-custom-price'
```

**Comment by akremstudy** [comment]
Caught this yesterday and will be fixed in one of the current pull requests once merged!
