### ISSUE TITLE
Multicall tips listener error

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#484]
Installed with `pip install telliot-feeds`
Versions: `telliot-core==0.1.7` `telliot-feeds==0.1.3`
start command: `telliot -a mumbai5 report -p YOLO`

*bug seems to be a problem on Mumbai only

Traceback: 
```
Traceback (most recent call last):
  File "/Users/sloetter/.pyenv/versions/3.9.13/bin/telliot", line 8, in <module>
    sys.exit(main())
  File "/Users/sloetter/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sloetter/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/sloetter/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sloetter/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sloetter/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sloetter/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sloetter/Projects/reportingDev/telliot-core/src/telliot_core/cli/utils.py", line 18, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/Users/sloetter/.pyenv/versions/3.9.13/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/sloetter/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/sloetter/Projects/reportingDev/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 446, in report
    await reporter.report()
  File "/Users/sloetter/Projects/reportingDev/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 455, in report
    _, _ = await self.report_once()
  File "/Users/sloetter/Projects/reportingDev/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 325, in report_once
    datafeed = await self.fetch_datafeed()
  File "/Users/sloetter/Projects/reportingDev/telliot-feeds/src/telliot_feeds/reporters/tellor_360.py", line 216, in fetch_datafeed
    suggested_feed, tip_amount = await get_feed_and_tip(self.autopay)
  File "/Users/sloetter/Projects/reportingDev/telliot-feeds/src/telliot_feeds/reporters/tips/suggest_datafeed.py", line 44, in get_feed_and_tip
    feed_tips = await funded_feeds.querydata_and_tip(current_time=current_timestamp)
  File "/Users/sloetter/Projects/reportingDev/telliot-feeds/src/telliot_feeds/reporters/tips/listener/funded_feeds.py", line 123, in querydata_and_tip
    eligible_funded_feeds, status = await self.filtered_funded_feeds(
  File "/Users/sloetter/Projects/reportingDev/telliot-feeds/src/telliot_feeds/reporters/tips/listener/funded_feeds.py", line 81, in filtered_funded_feeds
    feeds_timestsamps_and_values_lis, status = await self.multi_call.month_of_timestamps_and_values(
  File "/Users/sloetter/Projects/reportingDev/telliot-feeds/src/telliot_feeds/reporters/tips/multicall_functions/multicall_autopay.py", line 45, in month_of_timestamps_and_values
    values = multiple_values_response[("values_array", feed.query_id)]
KeyError: ('values_array', b'.\n\xa9\xe1\x9f\\>\x1d>\x08k4\xfe\x90\x07+C\x88\x93\x82\xf5c\xe4\x84\xe8\xe1\xe3X\x8b\x19\xef\x14')
/Users/sloetter/.pyenv/versions/3.9.13/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 10 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by oraclown** [comment]
Can you post the entire log (everything from when you invoked the above command)?

**Comment by spuddyminer** [comment]
[entire log.txt](https://github.com/tellor-io/telliot-feeds/files/10220225/entire.log.txt)

**Comment by spuddyminer** [comment]
the pip freeze from my git clone / editable install that works great:
[editable.txt](https://github.com/tellor-io/telliot-feeds/files/10220395/editable.txt)

pip freeze from the release install:
[release.txt](https://github.com/tellor-io/telliot-feeds/files/10220400/release.txt)

**Comment by oraclown** [comment]
I get the same error in the log file you included when I use the dependencies in `editable.txt`

**Comment by oraclown** [comment]
Since the issue has to do w/ multicall lib or something..

**Comment by oraclown** [comment]
when using `telliot -a dev-acct-bags report` it's not getting passed line:
```python
feed_tips = await funded_feeds.querydata_and_tip(current_time=current_timestamp)
```
And there's this obscure error which I need to find where it's originating from:
```console
{'code': -32000, 'message': 'out of gas'}
Multicall batch size reduced from 10000 to 6. The failed batch had 7 calls.
```

**Comment by oraclown** [comment]
this:
```console
{'code': -32000, 'message': 'out of gas'}
Multicall batch size reduced from 10000 to 6. The failed batch had 7 calls.
INFO    | telliot_feeds.sources.price_aggregator | Running median on [0.0483896, 0.048236214836716494, 0.04759]
INFO    | telliot_feeds.sources.price_aggregator | Feed Price: 0.048236214836716494 reported at time 2022-12-15 20:54:12.566653+00:00
INFO    | telliot_feeds.sources.price_aggregator | Number of sources used in aggregate: 3
INFO    | telliot_feeds.sources.price_aggregator | Running median on [0.04839084, 0.048236214836716494, 0.04759]
INFO    | telliot_feeds.sources.price_aggregator | Feed Price: 0.048236214836716494 reported at time 2022-12-15 20:54:13.919286+00:00
INFO    | telliot_feeds.sources.price_aggregator | Number of sources used in aggregate: 3
INFO    | telliot_feeds.sources.price_aggregator | Running median on [0.0483896, 0.048236214836716494, 0.04759]
INFO    | telliot_feeds.sources.price_aggregator | Feed Price: 0.048236214836716494 reported at time 2022-12-15 20:54:15.071880+00:00
INFO    | telliot_feeds.sources.price_aggregator | Number of sources used in aggregate: 3
INFO    | telliot_feeds.sources.price_aggregator | Running median on [0.04839084, 0.048236214836716494, 0.04759]
INFO    | telliot_feeds.sources.price_aggregator | Feed Price: 0.048236214836716494 reported at time 2022-12-15 20:54:16.316854+00:00
INFO    | telliot_feeds.sources.price_aggregator | Number of sources used in aggregate: 3
INFO    | telliot_feeds.sources.price_aggregator | Running median on [0.04839084, 0.048236214836716494, 0.04759]
INFO    | telliot_feeds.sources.price_aggregator | Feed Price: 0.048236214836716494 reported at time 2022-12-15 20:54:17.528991+00:00
INFO    | telliot_feeds.sources.price_aggregator | Number of sources used in aggregate: 3
INFO    | telliot_feeds.sources.price_aggregator | Running median on [0.0483896, 0.048236214836716494, 0.04759]
INFO    | telliot_feeds.sources.price_aggregator | Feed Price: 0.048236214836716494 reported at time 2022-12-15 20:54:18.713432+00:00
INFO    | telliot_feeds.sources.price_aggregator | Number of sources used in aggregate: 3
```
all is from:
```python
eligible_funded_feeds, status = await self.filtered_funded_feeds(
            now_timestamp=current_time, month_old_timestamp=one_month_ago
        )
```

**Comment by oraclown** [comment]
it's coming from:
```py
multiple_values_response, status = await self.multi_call(calls)
```
in `multicall_autopay.py`

**Comment by oraclown** [comment]
Tried reducing the hard-coded month time window that it checks. Reducing this window to one week or one day, doesn't change anything. Same error
```py
one_month_ago = current_time - 2_592_000
week_ago = current_time - 604_800
one_day_ago = current_time - 259_200
```

**Comment by oraclown** [comment]
spuddy says this only happens w/ mumbai reporters. makes me think it's the volume of stuff available that it's checking on mumbai autopay

**Comment by oraclown** [comment]
Tried w/ `multicall==0.6.1`, but get same error
