### ISSUE TITLE
Graceful exit of `telliot account status`

### ISSUE THREAD

**Issue by tallywiesenberg** [tellor-io/telliot-feeds#501]
input
```
(venv) m1 ➜  telliot-feed-examples (mimicry-impl) ✗ telliot account status
```
output
```
INFO    | telliot_core | telliot-core 0.1.7dev0
INFO    | telliot_core | Connected to eth-rinkeby [default account: rinkeby-tester], time: 2022-12-22 09:50:47.239082
ERROR   | telliot_core | Exception occurred in telliot-core app
ERROR   | telliot_core | <class 'Exception'>
ERROR   | telliot_core | No endpoints found
ERROR   | telliot_core | ['  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot_core/src/telliot_core/cli/commands/read.py", line 72, in get_staker_info\n    tellorx = core.get_tellorx_contracts()\n', '  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot_core/src/telliot_core/apps/core.py", line 120, in get_tellorx_contracts\n    master = TellorxMasterContract(node=self.endpoint, account=account)\n', '  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot_core/src/telliot_core/apps/core.py", line 183, in endpoint\n    self._endpoint = self.get_endpoint()\n', '  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot_core/src/telliot_core/apps/core.py", line 259, in get_endpoint\n    raise Exception("No endpoints found")\n']
Traceback (most recent call last):
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot-feed-examples/venv/bin/telliot", line 8, in <module>
    sys.exit(main())
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot-feed-examples/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot-feed-examples/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot-feed-examples/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot-feed-examples/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot-feed-examples/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot-feed-examples/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot-feed-examples/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot_core/src/telliot_core/cli/utils.py", line 18, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot_core/src/telliot_core/cli/commands/account.py", line 31, in status
    account_status, date_staked = await get_staker_info(ctx, account.address)
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot_core/src/telliot_core/cli/commands/read.py", line 72, in get_staker_info
    tellorx = core.get_tellorx_contracts()
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot_core/src/telliot_core/apps/core.py", line 120, in get_tellorx_contracts
    master = TellorxMasterContract(node=self.endpoint, account=account)
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot_core/src/telliot_core/apps/core.py", line 183, in endpoint
    self._endpoint = self.get_endpoint()
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot_core/src/telliot_core/apps/core.py", line 259, in get_endpoint
    raise Exception("No endpoints found")
Exception: No endpoints found
```

**Comment by tallywiesenberg** [comment]
version: `telliot-core 0.1.7dev0`

**Comment by oraclown** [comment]
There is no status command, no?
```console
$ telliot account --help
Usage: telliot account [OPTIONS] COMMAND [ARGS]...

  Create, find, and manage accounts.

Options:
  --help  Show this message and exit.

Commands:
  add     Add an account to the keystore.
  delete  Delete an account from the keystore.
  find    Search the keystore for accounts.
  key     Get the private key for an account.
```

**Comment by tallywiesenberg** [comment]
oh yeah ha
