### ISSUE TITLE
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary

### ISSUE THREAD

**Issue by tallywiesenberg** [tellor-io/telliot-feeds#502]
```
(venv) m1 ➜  telliot-feed-examples (mimicry-impl) ✗ telliot --help
Traceback (most recent call last):
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/bin/telliot", line 5, in <module>
    from telliot_feeds.cli.main import main
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot-feed-examples/src/telliot_feeds/cli/main.py", line 15, in <module>
    from telliot_feeds.cli.commands.query import query
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot-feed-examples/src/telliot_feeds/cli/commands/query.py", line 3, in <module>
    from telliot_feeds.cli.utils import build_query
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot-feed-examples/src/telliot_feeds/cli/utils.py", line 22, in <module>
    from telliot_feeds.feeds import DATAFEED_BUILDER_MAPPING
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot-feed-examples/src/telliot_feeds/feeds/__init__.py", line 33, in <module>
    from telliot_feeds.feeds.tellor_rng_feed import tellor_rng_feed
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot-feed-examples/src/telliot_feeds/feeds/tellor_rng_feed.py", line 9, in <module>
    from telliot_feeds.sources.blockhash_aggregator import TellorRNGManualSource
  File "/Users/tallywiesenberg/Repositories/Tellor/telliot/telliot-feed-examples/src/telliot_feeds/sources/blockhash_aggregator.py", line 25, in <module>
    cfg.get_endpoint().connect()
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/telliot_core/model/endpoints.py", line 70, in connect
    connected = self._web3.eth.get_block_number() > 1
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/middleware/formatting.py", line 94, in middleware
    response = make_request(method, params)
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/providers/websocket.py", line 144, in make_request
    return future.result()
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/providers/websocket.py", line 124, in coro_make_request
    async with self.conn as conn:
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/providers/websocket.py", line 72, in __aenter__
    self.ws = await connect(
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/websockets/legacy/client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/asyncio/base_events.py", line 1080, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/asyncio/base_events.py", line 1098, in _create_connection_transport
    protocol = protocol_factory()
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/websockets/legacy/client.py", line 160, in __init__
    super().__init__(**kwargs)
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 154, in __init__
    self._drain_lock = asyncio.Lock(
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/asyncio/locks.py", line 77, in __init__
    super().__init__(loop=loop)
  File "/Users/tallywiesenberg/.pyenv/versions/3.10.2/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary
```

versions:
```
Python 3.10
telliot-core==0.1.7
-e git+https://github.com/tellor-io/telliot-feeds.git@842f1880d30816b3e153e0942a38bc27017eace1#egg=telliot_feeds
```

**Comment by tallywiesenberg** [comment]
I think this expression
```python
cfg = TelliotConfig()
cfg.main.chain_id = 1
cfg.get_endpoint().connect()
w3 = cfg.get_endpoint().web3
``` in `src/telliot_feeds/sources/blockhash_aggregator.py` should be wrapped in a try catch clause

**Comment by akremstudy** [comment]
was fixed in a pr thats been merged!
