### ISSUE TITLE
AttributeError('Cannot reassign members.')

### ISSUE THREAD

**Issue by tallywiesenberg** [tellor-io/telliot-feeds#515]
The commands `telliot config init` and `telliot -a acct1 report -ncr -qt trb-usd-spot` exit with `AttributeError('Cannot reassign members.')`

```sh
(tenv) m1 ➜  ~ telliot config init
server rejected WebSocket connection: HTTP 401
Could not connect to RPC endpoint at: wss://mainnet.infura.io/ws/v3/{INFURA_API_KEY}
Traceback (most recent call last):
  File "/Users/tallywiesenberg/tenv/bin/telliot", line 5, in <module>
    from telliot_feeds.cli.main import main
  File "/Users/tallywiesenberg/tenv/lib/python3.9/site-packages/telliot_feeds/cli/main.py", line 15, in <module>
    from telliot_feeds.cli.commands.report import report
  File "/Users/tallywiesenberg/tenv/lib/python3.9/site-packages/telliot_feeds/cli/commands/report.py", line 24, in <module>
    from telliot_feeds.integrations.diva_protocol.report import DIVAProtocolReporter
  File "/Users/tallywiesenberg/tenv/lib/python3.9/site-packages/telliot_feeds/integrations/diva_protocol/report.py", line 29, in <module>
    from telliot_feeds.reporters.tellor_360 import Tellor360Reporter
  File "/Users/tallywiesenberg/tenv/lib/python3.9/site-packages/telliot_feeds/reporters/tellor_360.py", line 16, in <module>
    from telliot_feeds.reporters.tellor_flex import TellorFlexReporter
  File "/Users/tallywiesenberg/tenv/lib/python3.9/site-packages/telliot_feeds/reporters/tellor_flex.py", line 22, in <module>
    from telliot_feeds.reporters.reporter_autopay_utils import autopay_suggested_report
  File "/Users/tallywiesenberg/tenv/lib/python3.9/site-packages/telliot_feeds/reporters/reporter_autopay_utils.py", line 26, in <module>
    from telliot_feeds.reporters.tips import CATALOG_QUERY_IDS
  File "/Users/tallywiesenberg/tenv/lib/python3.9/site-packages/telliot_feeds/reporters/tips/__init__.py", line 13, in <module>
    Network.Mumbai = 80001
  File "/Users/tallywiesenberg/.pyenv/versions/3.9.12/lib/python3.9/enum.py", line 472, in __setattr__
    raise AttributeError('Cannot reassign members.')
AttributeError: Cannot reassign members.
(tenv) m1 ➜  ~ python --version
Python 3.9.12
(tenv) m1 ➜  ~ pip freeze | grep "multicall"
multicall==0.7.0
(tenv) m1 ➜  ~ pip freeze | grep telliot
telliot-core==0.1.7
telliot-feeds==0.1.3
multicall==0.7.0
```
MAC m1

**Comment by akremstudy** [comment]
was fixed here #489

**Comment by tallywiesenberg** [comment]
Is this fixed, but not yet released @akremstudy ?

**Comment by oraclown** [comment]
Going to close since was handled by earlier issue and we're doing a release this wk
