### ISSUE TITLE
Make so user only has to setup endpoints for chain they'll be using

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#543]
Take this out of the getting started docs:
```
For the funcitonality of telliot feeds, Endpoints should be configured for both Ethereum mainnet and Goerli testnet. (even if you don't plan on reporting oracle data on those networks)
```

**Comment by oraclown** [comment]
Throws this error if you try to delete all the other endpoints:
```console
$ telliot config show
Traceback (most recent call last):
  File "/Users/***/tenv/bin/telliot", line 5, in <module>
    from telliot_feeds.cli.main import main
  File "/Users/***/tenv/lib/python3.9/site-packages/telliot_feeds/cli/main.py", line 15, in <module>
    from telliot_feeds.cli.commands.query import query
  File "/Users/***/tenv/lib/python3.9/site-packages/telliot_feeds/cli/commands/query.py", line 3, in <module>
    from telliot_feeds.cli.utils import build_query
  File "/Users/***/tenv/lib/python3.9/site-packages/telliot_feeds/cli/utils.py", line 21, in <module>
    from telliot_feeds.feeds import DATAFEED_BUILDER_MAPPING
  File "/Users/***/tenv/lib/python3.9/site-packages/telliot_feeds/feeds/init.py", line 32, in <module>
    from telliot_feeds.feeds.tellor_rng_feed import tellor_rng_feed
  File "/Users/***/tenv/lib/python3.9/site-packages/telliot_feeds/feeds/tellor_rng_feed.py", line 9, in <module>
    from telliot_feeds.sources.blockhash_aggregator import TellorRNGManualSource
  File "/Users/***/tenv/lib/python3.9/site-packages/telliot_feeds/sources/blockhash_aggregator.py", line 28, in <module>
    cfg.get_endpoint().connect()
  File "/Users/***/tenv/lib/python3.9/site-packages/telliot_core/apps/telliot_config.py", line 93, in get_endpoint
    raise ValueError(f"Endpoint not found for chain_id={self.main.chain_id}")
ValueError: Endpoint not found for chain_id=1
```
