### ISSUE TITLE
AttributeError:  Chiado Testnet

### ISSUE THREAD

**Issue by cryptobanjo** [tellor-io/telliot-feeds#564]
telliot-core==0.1.7
-e git+https://github.com/tellor-io/telliot-feeds.git@cabc0f288625ad04223988034d1ba14a89a48824#egg=telliot_feeds

(tenv) ➜  telliot-feeds git:(main) ✗ telliot -a mumb1 report  -ncr -qt doge-usd-spot 
Traceback (most recent call last):
  File "/Users/mikez/telliot-feeds/tenv/bin/telliot", line 5, in <module>
    from telliot_feeds.cli.main import main
  File "/Users/mikez/telliot-feeds/src/telliot_feeds/cli/main.py", line 16, in <module>
    from telliot_feeds.cli.commands.report import report
  File "/Users/mikez/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 24, in <module>
    from telliot_feeds.integrations.diva_protocol.report import DIVAProtocolReporter
  File "/Users/mikez/telliot-feeds/src/telliot_feeds/integrations/diva_protocol/report.py", line 29, in <module>
    from telliot_feeds.reporters.tellor_360 import Tellor360Reporter
  File "/Users/mikez/telliot-feeds/src/telliot_feeds/reporters/tellor_360.py", line 15, in <module>
    from telliot_feeds.reporters.tellor_flex import TellorFlexReporter
  File "/Users/mikez/telliot-feeds/src/telliot_feeds/reporters/tellor_flex.py", line 22, in <module>
    from telliot_feeds.reporters.reporter_autopay_utils import autopay_suggested_report
  File "/Users/mikez/telliot-feeds/src/telliot_feeds/reporters/reporter_autopay_utils.py", line 26, in <module>
    from telliot_feeds.reporters.tips import CATALOG_QUERY_IDS
  File "/Users/mikez/telliot-feeds/src/telliot_feeds/reporters/tips/init.py", line 20, in <module>
    MULTICALL2_ADDRESSES[Network.ChiadoTestnet] = "0x959a437F1444DaDaC8aF997E71EAF0479c810267"
  File "/opt/homebrew/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/enum.py", line 429, in getattr
    raise AttributeError(name) from None
AttributeError: ChiadoTestnet

**Comment by akremstudy** [comment]
This isn't an issue in telliot. The address "0x959a437F1444DaDaC8aF997E71EAF0479c810267" isn't a correct address for a multicall that exists in Chiado. Telliot has the right address, this looks like an attempt to add Chiado prior to support for that network was added.
