### ISSUE TITLE
TypeError: '>=' not supported between instances of 'NoneType' and 'float'

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-feeds#648]
Just had this error pop up while reporting on polygon (listening for tips) with start command:
`telliot report -a polygon1 -wp 60`

versions:
telliot-core.git@7adc3a4bb83e313c45b4936837db51ca9f014e0a
telliot-feeds.git@13289b0c3eb50642462c701011f63b8d15af1ad5

```
ERROR   | telliot_feeds.sources.mimicry.nft_market_index | Failed to fetch collections details from NFTGo API.
ERROR   | telliot_core | Exception occurred in telliot-core app
ERROR   | telliot_core | <class 'TypeError'>
ERROR   | telliot_core | '>=' not supported between instances of 'NoneType' and 'float'
ERROR   | telliot_core | ['  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 496, in report\n    await reporter.report()\n', '  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 511, in report\n    _, _ = await self.report_once()\n', '  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 366, in report_once\n    datafeed = await self.fetch_datafeed()\n', '  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/tellor_360.py", line 282, in fetch_datafeed\n    suggested_feed, tip_amount = await get_feed_and_tip(self.autopay)\n', '  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/tips/suggest_datafeed.py", line 44, in get_feed_and_tip\n    feed_tips = await funded_feeds.querydata_and_tip(current_time=current_timestamp)\n', '  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/tips/listener/funded_feeds.py", line 133, in querydata_and_tip\n    eligible_funded_feeds, status = await self.filtered_funded_feeds(\n', '  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/tips/listener/funded_feeds.py", line 97, in filtered_funded_feeds\n    feeds_timestsamps_and_values_filtered = await self.window_and_priceThreshold_unmet_filter(\n', '  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/tips/listener/funded_feeds_filter.py", line 225, in window_and_priceThreshold_unmet_filter\n    price_change = await self.price_change(\n', '  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/tips/listener/funded_feeds_filter.py", line 98, in price_change\n    return _get_price_change(previous_val=value_before, current_val=self.prices[query_id])\n', '  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/tips/listener/funded_feeds_filter.py", line 251, in _get_price_change\n    elif current_val >= previous_val:\n']
Traceback (most recent call last):
  File "/home/ubuntu/tenv/bin/telliot", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/tenv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/telliot-core/src/telliot_core/cli/utils.py", line 18, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 496, in report
    await reporter.report()
  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 511, in report
    _, _ = await self.report_once()
  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 366, in report_once
    datafeed = await self.fetch_datafeed()
  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/tellor_360.py", line 282, in fetch_datafeed
    suggested_feed, tip_amount = await get_feed_and_tip(self.autopay)
  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/tips/suggest_datafeed.py", line 44, in get_feed_and_tip
    feed_tips = await funded_feeds.querydata_and_tip(current_time=current_timestamp)
  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/tips/listener/funded_feeds.py", line 133, in querydata_and_tip
    eligible_funded_feeds, status = await self.filtered_funded_feeds(
  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/tips/listener/funded_feeds.py", line 97, in filtered_funded_feeds
    feeds_timestsamps_and_values_filtered = await self.window_and_priceThreshold_unmet_filter(
  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/tips/listener/funded_feeds_filter.py", line 225, in window_and_priceThreshold_unmet_filter
    price_change = await self.price_change(
  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/tips/listener/funded_feeds_filter.py", line 98, in price_change
    return _get_price_change(previous_val=value_before, current_val=self.prices[query_id])
  File "/home/ubuntu/telliot-feeds/src/telliot_feeds/reporters/tips/listener/funded_feeds_filter.py", line 251, in _get_price_change
    elif current_val >= previous_val:
TypeError: '>=' not supported between instances of 'NoneType' and 'float'
```

**Comment by spuddyminer** [comment]
I believe this was resolved by adding the NFTgo api to the  `api_keys.yaml` config file.
